apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/alias
      value: eks-metrics-dev
    - op: add
      path: /spec/tags/Environment
      value: dev
  target:
    kind: Workspace
    name: eks-metrics
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: ack-system
  target:
    kind: Workspace
