apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ack-system
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/alias
      value: eks-metrics-prod
    - op: add
      path: /spec/tags/Environment
      value: prod
  target:
    kind: Workspace
    name: eks-metrics
